name: Go CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.0'
        cache: true

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.61


    - name: Run Tests and Build
      run: go test -v -coverprofile=coverage.out -covermode=count ./...

    - name: Go Coverage Report
      uses: ncruces/go-coverage-report@v0
      with:
        report: 'true' 
        chart: 'true' 
        amend: 'true'
      if: github.event_name == 'push'
